%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% File generated by IDL2Matlab V2.0.      %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%** ********
%**
function desstest()

  global i2mvs_p i2mvs_x i2mvs_y i2mvs_z % SYSTEM VARIABLES

  global win1 win2 labl  %% desstest

  if (xregistered('desstest'))
    return;
  end%if

  device('decomposed', 0);
  base = widget_base('title', 'desstest', 'column', 1);
  [row1, base] = widget_base('I2M_a1', base, 'row', 1, 'I2M_pos', [1]);
  [but11, row1] = widget_button('I2M_a1', row1, 'value', 'plot', 'uvalue', 'plot', 'I2M_pos', [1]);
  [but12, row1] = widget_button('I2M_a1', row1, 'value', 'oploterr', 'uvalue', 'oploterr', 'I2M_pos', [1]);
  [but13, row1] = widget_button('I2M_a1', row1, 'value', 'surface', 'uvalue', 'surface', 'I2M_pos', [1]);
  [but14, row1] = widget_button('I2M_a1', row1, 'value', 'shade_surf', 'uvalue', 'shade_surf', 'I2M_pos', [1]);
  [but15, row1] = widget_button('I2M_a1', row1, 'value', 'live_contour', 'uvalue', 'live_contour', 'I2M_pos', [1]);
  [but16, row1] = widget_button('I2M_a1', row1, 'value', 'erase', 'uvalue', 'erase', 'I2M_pos', [1]);
  [but10, row1] = widget_button('I2M_a1', row1, 'value', 'contour', 'uvalue', 'contour', 'I2M_pos', [1]);
  [list1, row1] = widget_droplist('I2M_a1', row1, 'value', d1_array('B-W LINEAR','BLUE/WHITE','RED TEMPERATURE','STD GAMMA-II','RED_PURPLE','BLUE-RED','RAINBOW','Pastels'), 'uvalue', 'loadct', 'I2M_pos', [1]);
  [row2, base] = widget_base('I2M_a1', base, 'row', 1, 'I2M_pos', [1]);
  [but17, row2] = widget_button('I2M_a1', row2, 'value', 'tvscl', 'uvalue', 'tvscl', 'I2M_pos', [1]);
  [but18, row2] = widget_button('I2M_a1', row2, 'value', 'image_cont', 'uvalue', 'image_cont', 'I2M_pos', [1]);
  [but19, row2] = widget_button('I2M_a1', row2, 'value', 'replot', 'uvalue', 'replot', 'I2M_pos', [1]);
  [but23, row2] = widget_button('I2M_a1', row2, 'value', '!P.background', 'uvalue', 'background', 'I2M_pos', [1]);
  [but24, row2] = widget_button('I2M_a1', row2, 'value', '!P.ticklen', 'uvalue', 'ticklen', 'I2M_pos', [1]);
  [but25, row2] = widget_button('I2M_a1', row2, 'value', '!P.linestyle', 'uvalue', 'linestyle', 'I2M_pos', [1]);
  [buex, base] = widget_base('I2M_a1', base, 'row', 1, 'exclusive', 1, 'I2M_pos', [1]);
  [but21, buex] = widget_button('I2M_a1', buex, 'value', 'Use Win#1   ', 'uvalue', 'win1', 'no_release', 1, 'I2M_pos', [1]);
  [but22, buex] = widget_button('I2M_a1', buex, 'value', 'Use Win#2   ', 'uvalue', 'win2', 'no_release', 1, 'I2M_pos', [1]);
  [labl, base] = widget_label('I2M_a1', base, 'xsize', 600, 'value', ' ', 'I2M_pos', [1]);
  [row3, base] = widget_base('I2M_a1', base, 'row', 1, 'I2M_pos', [1]);
  [draw1, row3] = widget_draw('I2M_a1', row3, 'xsize', 300, 'ysize', 250, 'button_event', 1, 'motion_event', 1, 'uvalue', 'winevent1', 'retain', 2, 'colors', -10, 'I2M_pos', [1]);
  [draw2, row3] = widget_draw('I2M_a1', row3, 'xsize', 300, 'ysize', 250, 'button_event', 1, 'motion_event', 1, 'uvalue', 'winevent2', 'retain', 2, 'I2M_pos', [1]);
  [base] = widget_control('I2M_a1', base, 'realize', 1, 'I2M_pos', [1]);
  [but21] = widget_control('I2M_a1', but21, 'set_button', 1, 'I2M_pos', [1]);
  [draw1, win1] = widget_control('I2M_a1', draw1, 'get_value', win1, 'I2M_pos', [1, 2]);
  [draw2, win2] = widget_control('I2M_a1', draw2, 'get_value', win2, 'I2M_pos', [1, 2]);
  win2 = win2;
  [base] = xmanager('I2M_a1', 'desstest', 'I2M_a2', base, 'no_block', 1, 'I2M_pos', [2]);
  wset(win1);
  i2mvs_p.title = 'Test DESS-GI (variable systeme)';
  i2mvs_x.title = 'This is X';
  i2mvs_y.title = 'This is Y';
  i2mvs_z.title = 'This is Z';
  i2mvs_p.subtitle = 'Sub_title';
  i2mvs_p.charsize = .6;

return;
%!x.style	=1
%!y.style	=1
%!z.style	=1
%% end of function desstest
