%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% File generated by IDL2Matlab v1.1. %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function essai()

  a = findgen(100);
  [a] = plott2('I2M_a1', a, 'title', 'titre', 'I2M_pos', [1]);
  b = 20;
  c = 15;
  xyouts('I2M_a1', 70, 'I2M_a2', 10, 'I2M_a3', 'testage', 'charsize', -1);
  xyouts('I2M_a1', 70, 'I2M_a2', 30, 'I2M_a3', 'testage', 'charsize', 2);
  xyouts('I2M_a1', 70, 'I2M_a2', 35, 'I2M_a3', 'testage', 'charsize', 1.45);
  xyouts('I2M_a1', 70, 'I2M_a2', 40, 'I2M_a3', 'testage', 'charsize', 3.5);
  xyouts('I2M_a1', 70, 'I2M_a2', 60, 'I2M_a3', 'testage', 'charsize', 3);
  xyouts('I2M_a1', 70, 'I2M_a2', 70, 'I2M_a3', 'testage', 'charsize', 0);

return;
% end of function essai
