%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% File generated by IDL2Matlab v1.1. %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%  commentaire
function essaiplot()

  b = 2;
  % Commentaire
  a = findgen(100);
  [a] = plott2('I2M_a1', a, 'I2M_a2', a.^b, 'xtitle', 'axe des x !!', 'psym', 3, 'linestyle', 3, 'ytitle', 'axe des y', 'title', 'ceci est le titre', 'polar', 1, 'I2M_pos', [1]);

return;
% plot, a, a^b, TITLE='test', PSYM=0
% end of function essaiplot
