%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% File generated by IDL2Matlab v1.1. %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function testcontour()

	[x,y] = meshgrid(-2:0.2:2,-2:0.2:3);
%  x = matx(21,26,-2,0.2);
%  y = maty(21,26,-2,0.2);
  z = x .* exp(-x.^2 - y.^2);
  v = d1_array(-0.3,-0.2,0,0.1,0.3,0.35,0.36);
  window(1);
  [z, x, y, v] = contourr('I2M_a1', z, 'I2M_a2', x, 'I2M_a3', y, 'levels', v, 'c_linestyle', d1_array(0,1,2,3), 'c_annotation', d1_array('n1','n2','n3','n4'), 'follow', 1, 'I2M_pos', [1, 2, 3, 4]);
  window(2);
  [z, x, y, v] = contourr('I2M_a1', z, 'I2M_a2', x, 'I2M_a3', y, 'levels', v, 'c_thick', d1_array(1,2,3), 'c_labels', d1_array(0,0,0,1,1,1), 'c_charsize', 1.1, 'I2M_pos', [1, 2, 3, 4]);
  window(3);
  [z, x, y] = contourr('I2M_a1', z, 'I2M_a2', x, 'I2M_a3', y, 'nlevels', 13, 'I2M_pos', [1, 2, 3]);
  window(4);
  [z, x, y, v] = contourr('I2M_a1', z, 'I2M_a2', x, 'I2M_a3', y, 'nlevels', 13, 'levels', v, 'follow', 1, 'I2M_pos', [1, 2, 3, 5]);
  window(5);
  [z, x, y] = contourr('I2M_a1', z, 'I2M_a2', x, 'I2M_a3', y, 'nlevels', 13, 'xlog', 1, 'ylog', 1, 'I2M_pos', [1, 2, 3]);
  window(6);
  [z, x, y] = contourr('I2M_a1', z, 'I2M_a2', x, 'I2M_a3', y, 'nlevels', 13, 'isotropic', 1, 'I2M_pos', [1, 2, 3]);
  window(7);
  [z, x, y] = contourr('I2M_a1', z, 'I2M_a2', x, 'I2M_a3', y, 'nlevels', 13, 'fill', 1, 'I2M_pos', [1, 2, 3]);
  window(8);
  [z, x, y] = contourr('I2M_a1', z, 'I2M_a2', x, 'I2M_a3', y, 'nlevels', 13, 'cell_fill', 1, 'I2M_pos', [1, 2, 3]);
  window(9);
  [z, x, y] = contourr('I2M_a1', z, 'I2M_a2', x, 'I2M_a3', y, 'nlevels', 13, 'fill', 1, 'cell_fill', 1, 'I2M_pos', [1, 2, 3]);
  window(10);
  [z, x, y] = contourr('I2M_a1', z, 'I2M_a2', x, 'I2M_a3', y, 'nlevels', 13, 'fill', 1, 'cell_fill', 1, 'c_labels', d1_array(0,0,0,1,1,1,1), 'c_annotation', d1_array('n1','n2','n3','n4'), 'c_linestyle', d1_array(0,1,2,3), 'I2M_pos', [1, 2, 3]);
  window(11);
  [z, x, y] = contourr('I2M_a1', z, 'I2M_a2', x, 'I2M_a3', y, 'nlevels', 13, 'fill', 1, 'cell_fill', 1, 'xlog', 1, 'ylog', 1, 'isotropic', 1, 'follow', 1, 'I2M_pos', [1, 2, 3]);
  window(12);
  [z, x, y] = contourr('I2M_a1', z, 'I2M_a2', x, 'I2M_a3', y, 'nlevels', 13, 'max_value', 0, 'follow', 1, 'I2M_pos', [1, 2, 3]);
  window(13);
  [z, x, y] = contourr('I2M_a1', z, 'I2M_a2', x, 'I2M_a3', y, 'nlevels', 13, 'min_value', 0, 'follow', 1, 'I2M_pos', [1, 2, 3]);
  window(14);
  [z, x, y] = contourr('I2M_a1', z, 'I2M_a2', x, 'I2M_a3', y, 'nlevels', 13, 'min_value', -0.2, 'max_value', 0.3, 'follow', 1, 'I2M_pos', [1, 2, 3]);
  [z, x, y, v] = contourr('I2M_a1', z, 'I2M_a2', x, 'I2M_a3', y, 'levels', v, 'c_linestyle', d1_array(1), 'overplot', 1, 'I2M_pos', [1, 2, 3, 4]);
  window(15);
  [z, x, y] = contourr('I2M_a1', z, 'I2M_a2', x, 'I2M_a3', y, 'nlevels', 13, 'downhill', 1, 'I2M_pos', [1, 2, 3]);
  window(16);
  [z, x, y, v] = contourr('I2M_a1', z, 'I2M_a2', x, 'I2M_a3', y, 'nlevels', 13, 'levels', v, 'min_value', -0.1, 'max_value', 0.3, 'c_charsize', 1, 'c_thick', d1_array(1,2), 'c_linestyle', d1_array(0,1), 'follow', 1, 'I2M_pos', [1, 2, 3, 5]);
  d=[[16,2,3,13];[5,11,10,8];[9,7,6,12];[4,14,15,1]];
% 	d = d1_array(16,2,3,13,5,11,10,8,9,7,6,12,4,14,15,1);
  window(17);
  [d] = contourr('I2M_a1', d, 'nlevels', 11, 'fill', 1, 'I2M_pos', [1]);
  window(18);
  [d] = contourr('I2M_a1', d, 'nlevels', 11, 'fill', 1, 'downhill', 1, 'I2M_pos', [1]);

return;
% end of function testcontour
