%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% File generated by IDL2Matlab v1.1. %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function testticklen()

  global i2mvs_p % SYSTEM VARIABLES

  x = findgen(100);
  y = x.^2 - x + 5;
  d = dist(25);
  i2mvs_p.linestyle = 3;
  i2mvs_p.psym = 0;
  window(1);
  [d] = surfacee('I2M_a1', d, 'title', 'Linestyle = 5', 'linestyle', 5, 'I2M_pos', [1]);
  window(2);
  [d] = plott('I2M_a1', d, 'title', 'linestyle = 1', 'linestyle', 1, 'I2M_pos', [1]);
  [y] = oplott('I2M_a1', y, 'title', 'linestyle = 3', 'I2M_pos', [1]);
  oplott('I2M_a1', 2 .* y, 'thick', 2, 'title', 'linestyle = 2 et psym = 3', 'linestyle', 2, 'psym', 3);
  oplott('I2M_a1', 3 .* y, 'thick', 3, 'title', 'linestyle = 4 et psym = 5', 'linestyle', 4, 'psym', 5);
  i2mvs_p.linestyle = 0;

return;
% end of function testticklen
