%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% File generated by IDL2Matlab v1.1. %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function testytitle()

  global i2mvs_y % SYSTEM VARIABLES

  x = findgen(100);
  y = x.^2 - x + 5;
  window(1);
  i2mvs_y.title = '';
  [y] = plott('I2M_a1', y, 'ytitle', 'YOP !C keyword!!', 'I2M_pos', [1]);
  window(2);
  i2mvs_y.title = 'YOP !C Varsys!!';
  [y] = plott('I2M_a1', y, 'ytitle', 'YOP !C keyword!!', 'I2M_pos', [1]);
  window(3);
  [y] = plott('I2M_a1', y, 'I2M_pos', [1]);

return;
% end of function testytitle
