%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% File generated by IDL2Matlab v1.1. %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function testloadct()

  global i2mvs_p % SYSTEM VARIABLES

  % Creation of undeclared variables of functions parameters
  d=1; 

  i2mvs_p.multi = d1_array(0,2,3,0,0);
  t = 4;
  [t] = loadct('I2M_a1', t, 'silent', 1, 'I2M_pos', [1]);
  shade_surf(dist(25));
  [d] = loadct('get_names', d, 'I2M_pos', [1]);
  % loadct, file = 'colors2.tbl'
  [d] = printt('I2M_a1', d, 'I2M_pos', [1]);
  loadct('I2M_a1', 0, 'bottom', 250);
  shade_surf(dist(25));
  loadct(0);
  loadct('I2M_a1', 15, 'ncolors', 15);
  shade_surf(dist(25));
  loadct(0);
  loadct('I2M_a1', 13, 'bottom', 245, 'ncolors', 5);
  shade_surf(dist(25));
  loadct(0);
  loadct('I2M_a1', 26, 'bottom', 245, 'ncolors', 40);
  shade_surf(dist(25));

return;
% end of function testloadct
