%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% File generated by IDL2Matlab V2.0.      %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function testplot()

  x = findgen(100);
  y = 2 .* x + 14;
  window(1);
  [y] = plott('I2M_a1', y, 'I2M_pos', [1]);
  window(2);
  [y] = plott('I2M_a1', y, 'thick', 4, 'I2M_pos', [1]);
  window(3);
  [y] = plott('I2M_a1', y, 'thick', 4, 'min_value', 50, 'I2M_pos', [1]);
  window(4);
  [y] = plott('I2M_a1', y, 'thick', 4, 'min_value', 50, 'max_value', 150, 'I2M_pos', [1]);
  window(5);
  [y] = plott('I2M_a1', y, 'thick', 4, 'min_value', 50, 'max_value', 150, 'ynozero', 1, 'I2M_pos', [1]);
  window(6);
  [y] = plott('I2M_a1', y, 'thick', 4, 'min_value', 50, 'max_value', 150, 'ynozero', 1, 'isotropic', 1, 'I2M_pos', [1]);
  window(7);
  [y] = plott('I2M_a1', y, 'thick', 4, 'min_value', 50, 'max_value', 150, 'ylog', 1, 'I2M_pos', [1]);
  window(8);
  [y] = plott('I2M_a1', y, 'thick', 4, 'min_value', 50, 'max_value', 150, 'xlog', 1, 'I2M_pos', [1]);
  window(9);
  [y] = plott('I2M_a1', y, 'thick', 4, 'min_value', 50, 'max_value', 150, 'ylog', 1, 'xlog', 1, 'I2M_pos', [1]);
  window(10);
  [y] = plott('I2M_a1', y, 'I2M_a2', y, 'polar', 1, 'I2M_pos', [1]);
  window(11);
  [y] = plott('I2M_a1', y, 'I2M_a2', y, 'polar', 1, 'thick', 2, 'min_value', 10, 'ylog', 1, 'I2M_pos', [1]);
  window(12);
  [y] = plott('I2M_a1', y, 'I2M_a2', y, 'polar', 1, 'thick', 2, 'min_value', 10, 'isotropic', 1, 'I2M_pos', [1]);
  window(13);
  [y] = plott('I2M_a1', y, 'I2M_a2', y, 'polar', 1, 'thick', 2, 'min_value', 10, 'ylog', 1, 'ynozero', 1, 'I2M_pos', [1]);

return;
%% end of function testplot
