%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% File generated by IDL2Matlab v1.1. %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function testsymsize()

  global i2mvs_p % SYSTEM VARIABLES

  x = findgen(10);
  i2mvs_p.multi = d1_array(0,2,0,0,1);
  [x] = plott('I2M_a1', x, 'psym', 2, 'symsize', 3, 'I2M_pos', [1]);
  plotts('I2M_a1', 2, 'I2M_a2', 3, 'psym', 1, 'symsize', 4);
  plotts('I2M_a1', 4, 'I2M_a2', 5, 'continue', 1, 'psym', 1, 'symsize', 10);
  plotts('I2M_a1', 4, 'I2M_a2', 8, 'continue', 1, 'psym', 5, 'symsize', 2);
  [x] = plott('I2M_a1', x, 'I2M_pos', [1]);
  i2mvs_p.multi = 0;

return;
% end of function testsymsize
