%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% File generated by IDL2Matlab v1.1. %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function testxminor()

  global i2mvs_p i2mvs_x % SYSTEM VARIABLES

  x = findgen(10);
  d = dist(25);
  window(0);
  i2mvs_p.multi = d1_array(0,2,0,0,1);
  [x] = plott('I2M_a1', x, 'xminor', -1, 'xtitle', 'KG xminor = -1', 'I2M_pos', [1]);
  oplott(x + 10);
  i2mvs_x.minor = -1;
  [x] = plott('I2M_a1', x, 'xminor', 0, 'xtitle', 'KG xminor = 0', 'I2M_pos', [1]);
  oplott(x + 10);
  window(1);
  i2mvs_x.minor = 2;
  [d] = contourr('I2M_a1', d, 'nlevels', 11, 'xtitle', 'KG xminor = -1', 'xminor', -1, 'I2M_pos', [1]);
  [d] = contourr('I2M_a1', d, 'nlevels', 11, 'xtitle', 'VS XMINOR = 2', 'I2M_pos', [1]);
  window(2);
  [d] = surfacee('I2M_a1', d, 'xminor', -0.5, 'xtitle', 'KG xminor = -0.5', 'I2M_pos', [1]);
  [d] = surfacee('I2M_a1', d, 'xminor', -1.5, 'xtitle', 'KG xminor = -1.5', 'I2M_pos', [1]);
  window(3);
  [d] = shade_surf('I2M_a1', d, 'xtitle', 'KG xminor = 1', 'xminor', 1, 'I2M_pos', [1]);
  i2mvs_x.minor = -1.5;
  [d] = shade_surf('I2M_a1', d, 'xtitle', 'VS xminor = -1.5', 'I2M_pos', [1]);
  i2mvs_p.multi = 0;
  i2mvs_x.minor = 0;

return;
% end of function testxminor
