%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% File generated by IDL2Matlab V2.0.      %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function testploterr()

  a = findgen(100);
  y = 3 .* a + 11;
  z = 2 .* a + 14;
  
  %[a, z] = plotterr('I2M_a1', a, 'I2M_a2', z, 'I2M_pos', [1, 2]);
  %[a, y] = plotterr('I2M_a1', a, 'I2M_a2', y, 'psym', 4, 'I2M_pos', [1, 2]);
  %[a, y] = plotterr('I2M_a1', a, 'I2M_a2', y, 'type', 3, 'I2M_pos', [1, 2]);
  %[a, y] = plotterr('I2M_a1', a, 'I2M_a2', y, 'psym', 4, 'type', 2, 'I2M_pos', [1, 2]);
  
  %[a, z, y] = plotterr('I2M_a1', a, 'I2M_a2', z, 'I2M_a3', y, 'I2M_pos', [1, 2, 3]);
  [a, z, y] = plotterr('I2M_a1', a, 'I2M_a2', z, 'I2M_a3', y, 'psym', 5, 'I2M_pos', [1, 2, 3]);
  %[a, z, y] = plotterr('I2M_a1', a, 'I2M_a2', z, 'I2M_a3', y, 'type', 2, 'I2M_pos', [1, 2, 3]);
  %[a, z, y] = plotterr('I2M_a1', a, 'I2M_a2', z, 'I2M_a3', y, 'psym', 5, 'type', 1, 'I2M_pos', [1, 2, 3]);

return;
% end of function testploterr
