%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% File generated by IDL2Matlab v1.1. %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function testbackground()

  global i2mvs_p % SYSTEM VARIABLES

  x = findgen(10);
  d = dist(25);
  red = d1_array(0,1,1,0,0,1);
  green = d1_array(0,1,0,1,0,1);
  blue = d1_array(0,1,0,0,1,0);
  tvlct(255 .* red,255 .* green,255 .* blue);
  window(1);
  i2mvs_p.multi = d1_array(0,2,0,0,1);
  [x] = plott('I2M_a1', x, 'background', 4, 'I2M_pos', [1]);
  oplott(x + 10);
  [d] = contourr('I2M_a1', d, 'nlevels', 11, 'background', 2, 'I2M_pos', [1]);
  window(2);
  i2mvs_p.multi = d1_array(0,2,2,5,0);
  [d] = shade_surf('I2M_a1', d, 'background', 5, 'I2M_pos', [1]);
  [d] = contourr('I2M_a1', d, 'nlevels', 11, 'background', 3, 'I2M_pos', [1]);
  i2mvs_p.multi = 0;
  window(3);
  [x] = plott('I2M_a1', x, 'background', 2, 'I2M_pos', [1]);

return;
% end of function testbackground
