%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% File generated by IDL2Matlab v1.1. %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function testtvlct()

  r = bytscl(sin(findgen(256)));
  g = bytscl(cos(findgen(256)));
  b = bindgen(256);
  [r] = printt('I2M_a1', r, 'I2M_pos', [1]);
  [r, g, b] = tvlct('I2M_a1', r, 'I2M_a2', g, 'I2M_a3', b, 'hsv', 1, 'I2M_pos', [1, 2, 3]);

return;
% end of function testtvlct
