%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% File generated by IDL2Matlab v1.1. %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function testthick()

  global i2mvs_p % SYSTEM VARIABLES

  x = findgen(100);
  y = x.^2 - x + 5;
  d = dist(25);
  i2mvs_p.multi = d1_array(0,2,2,0,0);
  i2mvs_p.thick = 1;
  [y] = plott('I2M_a1', y, 'I2M_pos', [1]);
  oplott('I2M_a1', 2 .* y, 'thick', 2);
  oplott('I2M_a1', 3 .* y, 'thick', 3);
  [x] = plott('I2M_a1', x, 'I2M_pos', [1]);
  plotts(20,22);
  plotts('I2M_a1', 40, 'I2M_a2', 50, 'continue', 1, 'thick', 2);
  plotts('I2M_a1', 40, 'I2M_a2', 80, 'continue', 1);
  plott(x.^2);

return;
% end of function testthick
