%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% File generated by IDL2Matlab v1.1. %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function testposition()

  global i2mvs_p % SYSTEM VARIABLES

  x = findgen(100);
  y = x.^2 - x + 5;
  c = d1_array(16,2,3,13,5,11,10,8,9,7,6,12,4,14,15,1);
  d = dist(25);
  i2mvs_p.position = d1_array(0,0,0.5,0.5);
  window(1);
  [d] = surfacee('I2M_a1', d, 'title', 'surface position=[0 0 1 1]', 'position', d1_array(0,0,1,1), 'I2M_pos', [1]);
  window(2);
  [d] = shade_surf('I2M_a1', d, 'title', 'shade surf position=[0.5,0.5,1,1]', 'position', d1_array(0.5,0.5,1,1), 'I2M_pos', [1]);
  window(3);
  [d] = contourr('I2M_a1', d, 'nlevels', 11, 'fill', 1, 'position', d1_array(0.2,0.5,0.8,0.8), 'title', 'position = [0.2,0.5,0.8,0.8]', 'I2M_pos', [1]);
  window(4);
  [y] = plott('I2M_a1', y, 'title', 'position = [0 0 0.5 0.5]', 'I2M_pos', [1]);
  oplott('I2M_a1', 2 .* y, 'thick', 2);
  oplott('I2M_a1', 3 .* y, 'thick', 3);
  i2mvs_p.position = 0;

return;
% end of function testposition
