%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% File generated by IDL2Matlab v1.1. %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function testlinestyle()

  global i2mvs_p % SYSTEM VARIABLES

  x = findgen(10);
  y = x.^2 - x + 5;
  d = dist(25);
  i2mvs_p.linestyle = 3;
  i2mvs_p.psym = 1;
  % window,1
  % surface, d, title='Linestyle = 5', linestyle = 5
  window(2);
  [x] = plott('I2M_a1', x, 'psym', 0, 'linestyle', 0, 'I2M_pos', [1]);
  oplott('I2M_a1', 2 .* x, 'thick', 2, 'linestyle', 2, 'psym', 3);
  oplott('I2M_a1', 3 .* x, 'thick', 3, 'linestyle', 4, 'psym', 5);
  i2mvs_p.linestyle = 0;

return;
% end of function testlinestyle
