%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% File generated by IDL2Matlab V2.0.      %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function test_shade_surf()

  global i2mvs_p % SYSTEM VARIABLES

  % Creation of undeclared variables of functions parameters
  img=1; 

  d = dist(30);
  s = sin(d);
  window(0);
  loadct(10);
  [d] = shade_surf('I2M_a1', d, 'shades', bytscl(s), 'I2M_pos', [1]);
  window(1);
  [d] = shade_surf('I2M_a1', d, 'save', 1, 'I2M_pos', [1]);
  printt(i2mvs_p.t);
  window(2);
  [d, img] = shade_surf('I2M_a1', d, 'ax', 25, 'az', 89, 'image', img, 'I2M_pos', [1, 4]);
  window(3);
  [d] = shade_surf('I2M_a1', d, 'max_value', 10, 'min_value', 5, 'I2M_pos', [1]);
  window(4);
  [d] = shade_surf('I2M_a1', d, 'xlog', 1, 'ylog', 1, 'I2M_pos', [1]);
  x = findgen(30).^2;
  y = findgen(30) .* 10 ./ 1.5;
  window(5);
  [d, x, y] = shade_surf('I2M_a1', d, 'I2M_a2', x, 'I2M_a3', y, 'shades', bytscl(s), 'ax', 50, 'save', 1, 'I2M_pos', [1, 2, 3]);
  printt(i2mvs_p.t);

return;
%% end of function test_shade_surf
