%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% File generated by IDL2Matlab v1.1. %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function testpsym()

  global i2mvs_p % SYSTEM VARIABLES

  x = findgen(100);
  y = x.^2 - x + 5;
  i2mvs_p.linestyle = 0;
  i2mvs_p.psym = 0;
  window(2);
  [x] = plott('I2M_a1', x, 'psym', 0, 'I2M_pos', [1]);
  plotts('I2M_a1', 20, 'I2M_a2', 22, 'psym', 1);
  plotts('I2M_a1', 40, 'I2M_a2', 50, 'continue', 1, 'psym', 5);
  plotts('I2M_a1', 40, 'I2M_a2', 80, 'continue', 1, 'psym', 0);
  i2mvs_p.psym = 0;

return;
% end of function testpsym
