%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% File generated by IDL2Matlab Mar20 2005 %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function essai()


  x = d1_array(1,2,3);
  y = 1;
  z = d4_array(d3_array(d2_array(d1_array(1,2),2,3)));
  [x] = printt('I2M_a1', x, 'I2M_pos', [1]);

return;
%% end of function essai
