%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% File generated by IDL2Matlab v1.1. %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%  $Id: dist.pro,v 1.2 1994/04/28 18:14:15 doug Exp $
% Return a rectangular array in which each pixel = euclidian
function a = dist(n,m)

  % distance from the corner.
  % +
  %  NAME:
  % 	DIST
  % 
  %  PURPOSE:
  % 	Create a rectangular array in which each element is proportional
  % 	to its frequency.  This array may be used for a variety
  % 	of purposes, including frequency-domain filtering and
  % 	making pretty pictures.
  % 
  %  CATEGORY:
  % 	Signal Processing.
  % 
  %  CALLING SEQUENCE:
  % 	Result = DIST(N [, M])
  % 
  %  INPUTS:
  % 	N = number of columns in result.
  % 	M = number of rows in result.  If omitted, N is used to return
  % 		a square array.
  % 
  %  OUTPUTS:
  % 	Returns an (N,M) floating array in which:
  % 
  % 	R(i,j) = SQRT(F(i)^2 + G(j)^2)   where:
  % 		 F(i) = i  IF 0 <= i <= n/2
  % 		      = n-i  IF i > n/2
  % 		 G(i) = i  IF 0 <= i <= m/2
  % 		      = m-i  IF i > m/2
  % 
  %  SIDE EFFECTS:
  % 	None.
  % 
  %  RESTRICTIONS:
  % 	None.
  % 
  %  PROCEDURE:
  % 	Straightforward.  The computation is done a row at a time.
  % 
  %  MODIFICATION HISTORY:
  % 	Very Old.
  %  	SMR, March 27, 1991 - Added the NOZERO keyword to increase efficiency.
  % 				(Recomended by Wayne Landsman)
  % 	DMS, July, 1992.  - Added M parameter to make non-square arrays.
  % -
  % Return to caller if an error occurs
  noop_p(2);
  % Make a row
  x = findgen(n);
  % column squares
  x = (min(x, (n - x))).^2;
  if (eval('n_elements(m)','0') <= 0)
    m = n;
  end %if
  % Make array
  a = fltarr(n,m,1);
  for i = 0:m ./ 2,
    % Row loop
    % Euclidian distance
    y = sqrt(x + i.^2);
    % Insert the row
    if i2msizz, y=y'; end;
    a(:,i +1) = y;
    if (i ~= 0)
      % Symmetrical
      a(:,m - i +1) = y;
    end %if
  end %for
  return;
% end of function dist
