////////////////////////////////////////////////
//// File generated by IDL2Matlab V2.0.     ////
////////////////////////////////////////////////

function essai()

  a = 8;
  [a] = test('I2M_a1', a, 'I2M_pos', [1]);
  disp(a);
  return;

return;
//// end of function essai
