PRO functions

print,' '
print,'*** Overview of functions for LAMP on D20SGI ***'
print,' '
print,'Type "result=function(parameter1,parameter2,keyword1=value1,/keyword2)" etc. '
print,' '
print,'IDL Internal functions:'
print,' '
print,'If you have XWindows or an emulator you may call "?" for the exhaustive IDL help '
print,' '
print,'indgen     : Creates an integer array with increasing numbers 0,1,2,3,...'
print,'             "x6=indgen(1600)" replaces the x-values (2theta) for workspace W6'
print,'             by the detector cell numbers (if W6 has 1600 points, of course) '
print,'fltarr     : Creates a floating point array, e.g. "a=fltarr(1600)"'
print,'where      : Gives the indices fullfilling a condition, e.g. "W6(WHERE(X6 LE 0))=W7(WHERE(X6 LE 0))"'
print,'             replaces for negative x-values (2theta) the counts in W6 by the counts in W7'
print,'sort       : Create a sorted list of indices of an array'
print,'smooth     : Smoothes an array'
print,'reform     : Change dimensions of an array but not the number of elements '
print,'n_elements : Give the number of elements of any variable'
print,'total      : Give the sum of an array, or an array containing the sum '
print,'             of rows or columns etc. of a multi-dimensional array '
print,' '
print,' '
print,' '
print,'LAMP Internal functions '
print,' '
print,'You may get more help by clicking on "The Manual" if you are working with the XWindows version '
print,'Otherwise you connect to the LAMP Manual of the Computing for Science group on WWW.ILL.FR '
print,'or you work on WebLamp on BARNS.ILL.FR where you will find a button called "Manual"'
print,' '
print,'rdrun : read a single numor'
print,'rdand : read several numors into a 2D-workspace'
print,'rdsum : read several numors and add them up into one 1D-workspace'
print,' '
print,' '
print,'D20 LAMP functions '
print,' '
print,'You may get more help by typing "function_name,help" '
print,'You find the files function_name.pro in the directory d20sgi.ill.fr:~lambda/macros '
print,' '
print,'monit    : Monitor and check your data and create catalogues'
print,'caliscan : Create the original powder pattern and the efficiencies from'
print,'           a calibration scan'
print,'rdprf    : Reads a profile file (output of fullprof), '
print,'           returns calculated diagram'   
print,' '
print,' '
END
