pro idl
print,' '
print,'*** TIPS and TRICKS on IDL - the language in which LAMP is written ***'
print,' '
print,'In LAMP you can use the whole power of IDL - LAMP itself is just a huge macro'
print,'You may find some help by typing "functions" or "procedures" to get help"
print,'for some internal IDL functions and procedures.'
print,'However there are some other syntax information you might want to know ...'
print,' '
print,'Capital letters'
print,' '
print,' Unlike UNIX or C, IDL is insensible to upper- or lowercase letters'
print,' '
print,'Operators :'
print,' ' 
print,' You may use operators in a very obvious way :'
print,' a=4+sin(23)^2*sqrt(9) - the result is in the variable a'
print,' ' 
print,'UNIX commands :'
print,' ' 
print,' You may call system commands by putting a "$" ahead :'
print,' "$ ls -l " will show you the content of your current directory'
print,' ' 
print,'Indices :'
print,' ' 
print,' Indices of arrays are given in round brackets, separated by comma:'
print,' a=fltarr(3,4) & a(0,*)=indgen(4) & print,a(0:1,0:2)'
print,' ' 
print,'Loops :'
print,' ' 
print,' In macros (see ~lambda/macros for examples) you may use for-do or do-while loops:'
print,' a=fltarr(3,4) & for i=0,3 do a(0,*)=i & print,a(0:1,0:2)'
print,' Only in macros you can put several commands in a loop:'
print,' pro mytest,count_to'
print,'   i=0'
print,'   do begin'
print,'     print,i'
print,'     i=i+1'
print,'   while i LE count_to'
print,' end'  
print,' This file called "mytest.pro" has to be in the directory you work in.'
print,' If you type now in LAMP "mytest,10" the procedure will count to 10.'
print,' If you change the file you have to recompile it, in the nowindows version'
print,' "lamp -nw" you type "ctrl-c", then ".run mytest", "retall" and "lamp",'
print,' then you care back in lamp and you will now work with the most recent version'
print,' of your macro.'
print,' '
print,'IF-conditions :'
print,' ' 
print,' In macros (see ~lambda/macros for examples) you may use if-clauses:'
print,' a=fltarr(3,4) & for i=0,3 do if i mod 2 ge 1 then a(0,*)=i & print,a(0:1,0:2)'
print,' Only in macros you can put several commands in a condition:'
print,' pro mytest,count_to'
print,'   i=0'
print,'   do begin'
print,'     if i mod 2 eq 0 then begin
print,'         print,i'
print,'     endif else begin  ' 
print,'         print,i," is odd"'
print,'     endelse '
print,'     i=i+1'
print,'   while i LE count_to'
print,' end'  
print,' This file called "mytest.pro" has to be in the directory you work in.'
print,' If you type now in LAMP "mytest,10" the procedure will count to 10.'
print,' If you change the file you have to recompile it, in the nowindows version'
print,' "lamp -nw" you type "ctrl-c", then ".run mytest", "retall" and "lamp",'
print,' then you care back in lamp and you will now work with the most recent version'
print,' of your macro.'
print,' '
end
