PRO procedures

print,' '
print,'*** Overview of procedures for LAMP on D20SGI ***'
print,' '
print,'Type "procedure,parameter1,parameter2,keyword1=value1,/keyword2" etc. '
print,' '
print,'IDL Internal procedures:'
print,' '
print,'If you have XWindows or an emulator you may call "?" for the exhaustive IDL help '
print,' '
print,'?        : Opens a help window (XWindows) on IDL - a really good help for IDL programmers!'
print,'help     : Gives informations (dimensions etc.) about any variable'
print,'           help,x6,w6,n6,p6,pv6 or help,/file'
print,'set_plot : Let you set your graphics device (Tektronix terminal, XWindows or PostScript'
print,'           set_plot,"tek", set_plot,"X" or set_plot,"ps"  '
print,'free_lun : Frees a logical unit (a file that has been opened for read or write'
print,'           but not yet closed, e.g. due to a program error) : If you receive '
print,'           e.g. an error message saying that "all logical units" are in use" you '
print,'           may type "help,/file" to get the logical unit numbers (e.g. 100 and 102)of the files concerned'
print,'           and you may close the files by typing "free_lun,100,102"'
print,'print    : Print any variable, string or value to the terminal window, also formatted'
print,'plot     : Plot a 1D-array, eventually dependent to an x-axis array'
print,'set_plot : Change the graphics output device, e.g. "X", "ps" or "tek" '
print,'journal  : Creates a journal file of your session. Every command you give will be written '
print,'           to a procedure file idlsave.pro or another filename you give'
print,'           till you leave lamp/idl or you type journal   '
print,'           without giving a filename '
print,' '
print,' '
print,'LAMP Internal procedures '
print,' '
print,'You may get more help by clicking on "The Manual" if you are working with the XWindows version '
print,'Otherwise (lamp -nw) you connect to the LAMP Manual of the Computing for Science group on WWW.ILL.FR '
print,'or you work with "WebLamp" on BARNS.ILL.FR where you will find a button called "Manual"'
print,' '
print,'rdset : Sets instrument, data base and cycle'
print,' '
print,' '
print,'D20 LAMP procedures '
print,' '
print,'You may get more help by typing "procedure_name,help" '
print,'You find the files procedure_name.pro in the directory d20sgi.ill.fr:~lambda/macros '
print,' '
print,'flag   : Choose several options to be applied during reading numors'
print,'exriet : Exports workspaces or numors to original Rietveld-Hewat format'
print,'         (INSTR 1 in fullprof, like D1A and D2B), general two axis '
print,'         diffractometer data format (INSTR 5) and GSAS formats'
print,'d20reg : Exports a 1D-workspace to x y dy format (gnuplot, xmgr)'
print,'         Corresponds to D4reg, extension "dat" will generate only one'
print,'         title comment line to correspond to fullprof format 10'
print,'fild20 : Exports 1D- or 2D-data (workspace or numors) in "D1B" format'
print,'par    : Prints the fixed parameters of a workspace or the variable'
print,'         parameters of a given step: "par,w6" or "par,w7,3"'
print,'rdeff  : Reads a calibration file (extension .d20)'
print,' '
END
