pro workspaces
print,'***************** What is a Workspace? ************************'
print,' '
print,'The so-called workspace is th major conception of LAMP.'
print,'Twenty workspaces W1 to W20 are disponible. '
print,'In each you may read your data, so generally neutron counting rates '
print,' '
print,'Each workspace, e.g. W6 (1D, 2D or even 3D ), goes together with further data'
print,'that have been read out from the raw data (numors).  '
print,' '
print,'In the case of a powder diffractometer you will store the twotheta values '
print,'for each detector cell in the array X6 - LAMP does it for you during  '
print,'reading in your numor(s). '
print,' '
print,'If you read in several numors or one numor containing several acquisitions  '
print,'(a scan or a multi-stroboscopic acquisition) there will be an array Y6 '
print,'containing e.g. the motor value for a motor scan  '
print,' '
print,'Even an array Z6 has been foreseen ... '
print,' '
print,'General parameters are stored in an 1D-array P6'
print,' '
print,'Variable parameters (several numors or acquisitions) are stored in PV6; '
print,'if W6 is two-dimensional (e.g. a scan), PV6 will be 2D as well and will'
print,'contain some variable parameters for each step of a scan (temperature, motors)'
print,' '
print,'N6 contains monitor information. For D20 it is already two-dimensional fo a   '
print,'single acquisition and 3D for a scan. N6(0,0,*) contains the monitor counting '
print,'rate eventually changed by a normalisation factor, N6(0,1,*) contains the '
print,'counting time in seconds, not changed, and N6(0,2,*) contains an optional '
print,'second monitor, eventually changed due to normalisation. Some operations '
print,'(substraction) are refused by LAMP, if the monitor of the two workspaces to '
print,'be compared are not equal. N7(0) has to be equal N6(0) before performing '
print,'W8=W7-W6 '
print,' '
print,'E6 contains the error (sigma) of counting rate. LAMP detects arithmetic '
print,'operations to workspaces and let the errors correctly follow up. However, not '
print,'all operations a user may imagine have been imagined by the auythors of LAMP, '
print,'so if you note a bug in error calculation, please inform the Computing for '
print,'Science!  '
print,' '
print,'W_TIT(6), OTHER_TIT(6), X_TIT(6), Y_TIT(6), Z_TIT(6), PAR_TXT(6,*) contain'
print,'title strings, axis labels and explainations to the fixed parameters of W6'
print,' '
end
